### PR TITLE
add smtplan+

### PR DESCRIPTION
**Pull request by jdekarske**
Inspired from some discussion [here](https://github.com/KCL-Planning/SMTPlan/issues/10).

The image is nearly 1GB for now. A multi stage build is likely a next step.

Would it be good practice to add the singularity definition file into the packages directory since this doesn't exist in the smtplan repo?

### CODE REVIEW

**Comment by haz** [comment]
Awesome! Thoughts...

- 1Gb is indeed a heavy hit. Have you taken a crack on some of the tips [here](https://github.com/AI-Planning/planutils/wiki/Building-Singularity-Images)?

- Should the package be `smtplan+` or `smtplan`? If it's all the same, the latter might be better. It means that it would be exposed as `.../smtplan/solve` in the upcoming replacement for the online solver.

- Not sure where the singularity image should live. I think not planutils...would adding just that file to the smtplan repo be viable as a PR? Does seem like the most natural place to me. It's the model FD follows: https://github.com/aibasel/downward/tree/main/misc/releases/20.06

**Comment by jdekarske** [comment]
We are down to 148 MB after a [multi-stage build](https://cloud.sylabs.io/library/_container/60f85f5bbc16537b1321c43b) :smile:. The solver binary is quite large and I don't plan on putting a lot of energy in to fixing that.

[KCL site](http://kcl-planning.github.io/SMTPlan/ ) says "SMTPlan+" 
[publication](https://planning.wiki/_citedpapers/smtplan2016.pdf) says "SMTPlan+"
[github repo](https://github.com/KCL-Planning/SMTPlan) is called "SMTPlan" and the binary is "SMTPlan", but the readme says "SMTPlan+"

I'll take this to mean we can use the name less the '+' for functional things, but keep it for documentation. I'm open to do whatever, and we can ping the KCL folks.

I PR'd to the [original repo](https://github.com/KCL-Planning/SMTPlan/pull/14) using the FD model.

**Comment by haz** [comment]
Awesome stuff! There's been some discussion on maybe just pulling images from dockerhub (there's a way to do it via singularity, and it rebuilds the docker container as a singularity one). For now, though, I see no reason we can't pull from your shub lib.

Only recommendation is to change the directory name -- from `smtplan+` to `smtplan`. It's the folder name (not the `.sif` name) that will count when we deploy.

**Comment by jdekarske** [comment]
Done!

>There's been some discussion on maybe just pulling images from dockerhub

That is actually what my [singularity definition](https://github.com/KCL-Planning/SMTPlan/pull/14/commits/194f90d1b0052dcad43ee66f6b9d83c87c7aad23) does (from my image on dockerhub).

**Comment by haz** [comment]
Sorry, one last thing! Can you put in the size for the manifest? You can see how lama is install...

```
$ lama domain.pddl problem.pddl

Package not installed!
  Download & install? [Y/n] y

About to install the following packages: downward (36M), lama (20K)
  Proceed? [Y/n] y
Installing downward...
INFO:    Downloading shub image
 35.88 MiB / 35.88 MiB [=======================================] 100.00% 3.99 MiB/s 8s
Finished installing downward (size: 36M)
Installing lama...
Finished installing lama (size: 20K)
Successfully installed lama!

Original command: lama
  Re-run command? [Y/n] y

Parsing...
$
```

...and its the `Finish installing smtplan (size: ???)` that you're looking for.

**Comment by haz** [comment]
All set, thanks!!

**Comment by haz** [comment]
You should be able to pull the latest now, with smtplan intact. Thanks again!

**Pull request merged**
