### PR TITLE
use multiple stages in Dockerfile

### PR DESCRIPTION
**Pull request by FlorianPommerening**
The current Dockerfile leads to a 1.5 GiB container and this patch cuts that down to 300 MiB. There are a couple of things I changed, some more controversial than others:

1. multi-stage build
The build is now done in two stages: the first builds singularity, the next copies it from the first. This way, you don't end up with go installed in the main container. It also means some build tools are no longer required.

2. golang container
The build now uses golang container instead of installing go from source. The advantage is that we don't have to care about the details of installing go and don't need its dependencies. We could go further in this direction by also not installing singularity from source but instead use the latest "slim" container from here https://github.com/singularityhub/singularity-docker I didn't do this so far but it might be worth a thought.

3. apt-get steps
One "trick" that is done quite often on Dockerfiles is to bundle `apt-get update`, `apt-get install` and `rm -rf /var/lib/apt/lists/*` into a single step. The point of that is that every `RUN` step in docker creates a new layer. The final image size is the sum of all layer sizes, so downloading the package info in one layer and deleting it in a later layer still uses the full space of it. Bundling the steps into one saves a bit of space over all.

4. removed packages
I wasn't clear on which packages where meant for the user and which where just dependencies. I removed a lot of non-essential packages where I thought they are not needed (hoping you'd correct me if I removed too much). For example, `flex` and `bison` where maybe thought for VAL, but VAL could also be build in a separate build stage or installed as a binary or singularity image and doesn't need those packages then. The remaining non-essential packages are `bash-completion`, `vim` and `wget` to make working inside the container more pleasant. I also left `python3-venv` which I assume was meant for lab? Though I'm not sure if this make sense because running experiments from inside the container is not ideal.

### CODE REVIEW

**Comment by haz** [comment]
1st stage packages don't make it to the 2nd stage, right? `unzip`, `curl`, and `git` likely all should be included in the 2nd stage as well.

As you point out, many of the previous ones are just there as defaults from FD's recommended list.

**Comment by FlorianPommerening** [comment]
Yes, the first stage is thrown away after the build (or could be at least, maybe docker caches it internally). I added the packages to the second stage as well. But isn't installing both `wget` and `curl` overkill? I thought curl was just there for the command installing go.

**Comment by haz** [comment]
You're right about curl. Generally, if a package is required for installing a wide variety of things (`wget`, `pip`, `git` all fall into that category), then it's probably worth having installed as part of the docker. Curl doesn't make the cut ;)

**Comment by FlorianPommerening** [comment]
Ok, I removed curl again. Either way, the docker container is a way of tracking/testing your dependencies: when you add new features to planutils and you make sure that they also run in the docker, then the list of installed packages in the main docker container act as a list of dependencies.

**Comment by haz** [comment]
Aye, exactly. Any suggestion on what we'd do for esoteric dependencies? I.e., those that only a particular package would require?

Imagine the `planutils --setup-server-environment`: It will need to install node.js and a host of other things. Just have those setup scripts as bash files that need root access to go?

**Comment by FlorianPommerening** [comment]
I am generally very careful with running scripts with root access, specifically when they make changes to my system (install software, etc.). Even ignoring the security issue, if some assumptions about my system are not correct, it can mess things up (I don't use bash for example, so writing things in my .bashrc does nothing, others might not use apt to install software, etc.). My point is that I wouldn't want a script to install node.js for me. Downloading a binary or a container is fine, building a container on my system is also fine, if the build is somewhat self-contained like the one by singularity. But installing software packages is a different issue for me.

I think a way around this would be to generate a script and let the user execute it themselves. If the script is simple enough, they can look through it and check that things match their system before they execute it. Another option (especially useful for servers) would be to have multiple dockerfiles for specific use cases: one dockerfile that is meant to run as a server, one that is meant for people windows who can run docker but no VMs (although, I would make vagrant the recommended default for those who can run it). They point of the server-docker would then not be to set up your server, i.e., make changes to your server setup, but the docker image itself would run as the server. I think the use cases for running a docker image as a server and running it locally are so different, it makes sense to separate them into two docker files.

**Comment by haz** [comment]
Much like the other issue, why not both?

I hear you on the hesitation for running planutils in sudo mode constantly. I like the idea of "Oh, you want to do that? Well it's a little admin'y, so here's a script you can run if you really want to."

Then, those scripts are precisely what can(/should) be used for the tailored images. I can imagine a Docker/VM build for developing FD (e.g., giving it to students in an AI course to implement their own heuristic as a project). One for the webserver version. One for running a variety of planners. Etc.

As a slight aside, the webserver setup is also one that many are asking for in their local environments. Not to host their own service, but rather to wrap their planners for connecting to other programs (the vscode and online editor plugins both support this as having localhost being the solver server).

Do you think the initial Linux setup should be placed in a common script, rather than mirroring the details in both the Dockerfile and Vagrant flavours?

**Comment by FlorianPommerening** [comment]
Yes, that sounds like a good idea. So to make sure, we are on the same page, is this what you meant:

- have a couple of scripts that set up different parts (install singularity, install node.js, etc.) 
- have different containers for different use cases (and a readme that explains which container is meant for what)
- inside the setup script for each container, call the appropriate scripts
- on a native installation (not in a container), don't call the scripts directly, but tell the user to run them, so they can check and possibly adapt them.

In that case, the details to iron out would be what/how many containers do you want and how should we group the scripts? For the first question, I guess it would make sense to open a new issue for each container (the discussion here went a bit off topic for the original pull request). The answer to the question which tasks to group in scripts probably comes naturally from that.

**Comment by haz** [comment]
Yes, and.

This is a relevant subset of the `planutils` initial idea (which is obviously something in flux / up for debate):

```
$ planutils --setup-server-environment
Setting up a webserver to call the installed planners...

$ planutils --setup-development-environment
Installing common dependencies for building planners...
Installing common planning libraries...
```

I would change the behaviour to be something like this...
```
$ planutils --setup-server-environment
Installation script created: setup_server.sh.
Please review the script and run it with administrator privileges.

$ sudo planutils --setup-development-environment --force
Installing common dependencies for building planners...
Installing common planning libraries...
```

And then in the docker files for a specific setup, we just run the `--force` version (maybe sudo isn't required there). There's an open question as to where those scripts live: string in a json config? files shipped with planutils?

The other question that I see being worth answering is the scope of scripts. I feel as though they should be mapped to specific environments (like the two examples above) rather than components of environments (like a script for just installing node.js). That make sense?

**Comment by FlorianPommerening** [comment]
That usage seems a bit complicated to me. Say I'm going to set up a server with some hosted planners. With what you are suggesting I'd first install pip, then use pip to install planutils, then use planutils to generate a script, then use that script to make the actual installation. I think a more straight-forward setup would be one where I download the script and run it. In this view, the direction would be flipped, instead of planutils installing the server environment, the script for the server environment would install planutils, node.js, singularity, etc. on my server. After this setup is done, I could use the installed planutils on the server to download the planner images I want to host on the server. This would be similar to the different containers/VMs: you don't use planutils to get the container but instead get the container directly and it contains planutils so inside the container you can use it to get planners, validators, etc.

This would put the server setup script on the same level as the containers: all of them would be different ways to give you a system ready to run planners, while planutils would be the way to get the planners in a unified way. I think then it also makes sense to offer the different setups in parallel: if you are on windows/mac and want solutions to planning tasks use the VM (or client-docker); if you are on a linux use the client-side installation script to install things natively; if you want to run a server host the server-docker or use the server-side installation script. Independent of that choice, you can afterwards use planutils to download and run planners and other tools.

To answer your question about the scope of the scripts: I think it would be good if we can split things up in a way that avoids duplication. So it makes sense to have a server-side setup script and call this from the server-docker, and have a client-side setup that is called from the client-side docker. But if both of them install singularity, then it would make sense to have just a single script for installing singularity. But the scripts could be a collection of scripts that are based on each other, so it wouldn't have to be a black-and-white decision.

**Comment by haz** [comment]
Very intriguing. Never thought of that inversion.

Scripts live in the `planutils` repo or elsewhere? A common practice for quick-and-easy installation is to host a script someplace that you can immediately download and run. Something like this would install docker (I may have the `sudo` in the wrong place):
`curl -fsSL https://get.docker.com | sudo sh`

So it would be convenient to have the scripts accessible for quick setup that way.

Either way, I like the idea!

**Comment by FlorianPommerening** [comment]
I like the idea of having them easily accessible but I think this is independent on where they are hosted. For example, you can have URLs point to the "raw" files in a github repository. Since the setup scripts and containers are likely to grow and change, I'd put them in a repository. I have no strong opinion on whether to keep them in this repository or create a new one for them.

**Comment by haz** [comment]
Ok, I'd probably advocate an `environments/` folder here in the `planutils` directory. Each sub-directory could contain `README.md`, `setup.sh`, and `Dockerfile` doing the obvious. Any objections/additions/modifications? I can give an initial one a go as an example...

Btw, I'll likely create an issue to cover this and point to the conversation here -- just so happened that it spawned out from a PR discussion that's long since been merged!

**Comment by FlorianPommerening** [comment]
Three addotions: first, I'd recommend one issue per environment instead of one issue for all of them (makes it easier to discuss them). Then the word "and" in "and `Dockerfile`" seems wrong. Aren't some of the environments VMs instead of Docker containers and some are scripts only. That brings me to my last point:: if every environment is its own directory, (how) are they sharing common code (like the script for installing singularity)?

**Comment by haz** [comment]
1. Fair enough.
2. Well a docker image for each environment, no? Additionally, a Vagrant file makes sense. Ultimately, they would be minimal wrappers to the script, which installs what's required (and thus potentially requires root).
3. Hrmz...hadn't considered it. If `source`ing is used, then the scripts could appear separately for re-use.

As a grounding, there are 3 environments already identified:
- **server**: useful both for turnkey deployment of solver in the cloud as well as running planners locally to connect to via API's (like the PDDL editors or other software with planners-in-the-loop)
- **development**: useful for building/developing planners and planner-related technology
- **evaluation**: useful for setting up everything required for evaluating (lab, API tools to fetch benchmarks, etc)

**Comment by FlorianPommerening** [comment]
Ahh, I see, you use a slightly different definition of "environment" then I did. I thought of "server (docker)" and "server (native)" as two separate environments. But I now see the advantage of treating them as one and just offering multiple ways to run the environment. Not all combinations make sense, though: 

- **server**: docker and native installation seem useful. I'm not sure about vagrant here. I think some servers are started as VMs but I don't know if the systems running the VMs typically support vagrant.
- **development**: native installation and vagrant seem like the way to go here. I'd say that docker is not meant for this use case, but it might still be an option for people running windows in a way that prohibits VMs.
- **evaluation**: this only makes sense locally without the overhead of docker or a VM. The only useful experiments you could do on a VM/docker would be ones that measure performance-independent data and are still fast enough to run on a single machine. If there is a virtualized environment like this, it should come with a big warning sign.

As for the sharing issue: this is a bit tricky for Docker because it only copies the files in the working directory to the build context and does not support symlinks for this. There are some options of how to handle this mentioned here: https://stackoverflow.com/questions/39376786/docker-and-symlinks
I think the options "Build script", "Build from URL", and "Increase the scope of the image build context" would work for us. Each one comes with its own set of disadvantages.

**Comment by haz** [comment]
Aye, definitely not all make sense. Even if I'd personally prefer to play with all of them in my Docker-in-Windows, it doesn't mean we need to ship versions that don't make sense. If we have a native script that can install, then that script can just as easily be run from within a Docker container.

I'm not sure we need Docker sharing -- only one it really makes sense for (as you point out) is the server one.

**Comment by FlorianPommerening** [comment]
Makes sense. lets start with just writing each environment independently and live with some duplicated code. If the duplication gets too bad, we can still think about how to fix it then.

**Comment by haz** [comment]
- #7: Server environment
- #9: Developer environment 
- #10: Evaluation environment

**Pull request merged**
