### PR TITLE
Entrypoints

### PR DESCRIPTION
**Pull request by guicho271828**
#43

### CODE REVIEW

**Comment by guicho271828** [comment]
just noticed that my cluster doesn't support singularity so this tool is not very useful with that assumption... sigh

**Comment by haz** [comment]
Is this PR now moot given #58 / #60 ? Nothing gets added to the path by default (other than the single `planutils` entrypoint), and then `planutils activate` adds _everything_ to the path. One could imagine an in-between, but this may be an option for installing _after_ planutils is in place. E.g., something like `planutils add-path` which just places those installed on the system PATH (hard to do that without assuming bash and augmenting the .bashrc).

**Comment by guicho271828** [comment]
> planutils activate

thanks for the info, let me check what it does

**Comment by haz** [comment]
Alright if I close this out? Things have moved on a fair bit since.

**Pull request closed without merging**
